# Phase4 Configuration

debug: false
log_level: info

audio:
  input_device: 6
  output_device: -1
  sample_rate: 44100
  frames_per_buffer: 256
  input_channels: 1 # MOVE: Mono input is sufficient for analysis, but need option for recording
  output_channels: 2 # Unused but sensible to leave in
  low_latency: false
  fft_window: "Hann" # Options: BartlettHann, Blackman, BlackmanNuttall, Hann, Hamming, Lanczos, Nuttall

transport:
  udp_enabled: true
  udp_target_address: "127.0.0.1:9090" # Target IP and port
  udp_send_interval: "16.7ms" # Target interval (~60Hz, think FPS not Sample Rate)

recording:
  enabled: false
  output_dir: "./recordings"
  format: wav
  bit_depth: 16
  max_duration_seconds: 0 # 0 for no limit
  silence_threshold: 0.01
