# Grec V2 Configuration

# General settings
debug: false
log_level: info

# FFT Analysis settings
analysis:
  fft:
    adaptive: true
    initial_size: 1024
    min_size: 256 # Don't go below this
    max_size: 4096 # Don't go above this
    size_cooldown_s: 3 # Three seconds between FFT size changes
    adaptive_period_ms: 500 # Half-second minimum between adaptations

# Duet3 settings
audio:
  use_default_devices: true
  input_device: 1
  sample_rate: 44100
  frames_per_buffer: 256
  channels: 2
  input_channels: 2
  output_channels: 2

# Microphone settings
# audio:
#   use_default_devices: true
#   input_device: 0
#   sample_rate: 44100
#   frames_per_buffer: 256
#   channels: 2
#   input_channels: 1
#   output_channels: 0

# Recording settings
recording:
  enabled: false
  output_dir: recordings
  format: wav
  bit_depth: 16
  silence_threshold: 0.01
